---
title: "COVID-19 Italy"
#subtitle: "Notes"
author: "P.Monticone & R.Valperga"
date: "`r Sys.Date()`"
output:
 prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: true
fontsize: 11pt
bibliography: bibliography.bibtex # https://doi2bib.org
biblio-style: apalike
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

# Articles 

### Il Sole 24 Ore


### Il Post 

* [Il metodo della Corea del Sud](https://www.ilpost.it/2020/04/05/coreano-del-sud-test-pandemia/)
* [Perché non stiamo facendo più tamponi?](https://www.ilpost.it/2020/04/04/coronavirus-tamponi-test-problemi-numero/)
* [I “guariti” annunciati dalla Protezione Civile ogni giorno non sono tutti guariti](https://www.ilpost.it/2020/04/02/guariti-coronavirus-protezione-civile/)
* [Quante sono davvero le persone contagiate?](https://www.ilpost.it/2020/03/31/contagi-coronavirus-imperial-college-london/)
* [La Lombardia non fa tutti i tamponi che dovrebbe](https://www.ilpost.it/2020/03/27/tamponi-lombardia-fontana-coronavirus/)
* [La differenza tra il numero di tamponi e il numero delle persone testate](https://www.ilpost.it/2020/03/26/coronavirus-tamponi-eseguiti-persone-testate/)

### La Voce
* [Decessi da Covid, facciamo chiarezza sui dati Istat](https://www.lavoce.info/archives/65042/decessi-da-covid-facciamo-chiarezza-sui-dati-istat/)
* [Morti da coronavirus: calcoli sul campione inadatto](https://www.lavoce.info/archives/65171/morti-da-coronavirus-calcoli-sul-campione-inadatto/)

### Medium 

* [Dov’è veramente il picco dei contagi? Analisi dei dati ISTAT sulla mortalità](https://medium.com/@pmeridian/dovè-veramente-il-picco-dei-contagi-analisi-dei-dati-istat-sulla-mortalità-26bfcab7f155)

#### Francesco Costa 

* [I dati ufficiali sono un’illusione ottica](https://www.francescocosta.net/2020/03/19/dati-ufficiali-illusione-ottica/)
* [Il famoso modello italiano](https://www.francescocosta.net/2020/03/30/famoso-modello-italiano/)
* [Non è il momento di dire bugie](https://www.francescocosta.net/2020/04/02/non-e-il-momento-di-dire-bugie/)


# Data & Protocols   

### Best Dashboards
* [WHO](https://experience.arcgis.com/experience/685d0ace521648f8a5beeeee1b9125cd)
* [PC](http://arcg.is/C1unv)
* [Google](https://datastudio.google.com/u/0/reporting/91350339-2c97-49b5-92b8-965996530f00/page/RdlHB)
* [Lab24](https://lab24.ilsole24ore.com/coronavirus/)
* [leoniDEV](https://covid19-ita.leonidev.com)
* [OWID](https://ourworldindata.org/coronavirus)

### Protezione Civile 
* [Github repository](https://github.com/pcm-dpc/COVID-19)
* [Dashboard (Desktop)](http://arcg.is/C1unv)
* [Dashboard (Mobile)](http://arcg.is/081a51)

### Istituto Superiore di Sanità 

* [Sythesis](https://www.epicentro.iss.it/coronavirus/)

### Ministero della Salute 

1. [Testing protocol, 27-02](http://www.trovanorme.salute.gov.it/norme/renderNormsanPdf?anno=2020&codLeg=73444&parte=1%20&serie=null)
1. [Testing protocol, 09-03](https://www.fnopi.it/wp-content/uploads/2020/03/Circolare_9_marzo_2020.pdf)
1. [Testing protocol, 03-04](http://www.trovanorme.salute.gov.it/norme/renderNormsanPdf?anno=2020&codLeg=73799&parte=1%20&serie=null)

### ISTAT

* [L’andamento dei decessi del 2020. Dati anticipatori sulla base del sistema ANPR, ISTAT]https://www.istat.it/it/archivio/240401





* [Pick of the coronavirus papers: Masks could cut spread of COVID-19 virus](https://www.nature.com/articles/d41586-020-00502-w?utm_source=twt_nnc&utm_medium=social&utm_campaign=naturenews&sf232387874=1)







# Video 

# Rest of the world

## America
### Canada 
* [Data per patient](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1310076601)

## Asia
### South Korea
* [KCDC](http://ncov.mohw.go.kr/en/)

## Europe 
* [ECDC](https://www.ecdc.europa.eu/en/covid-19-pandemic)

### Sweden
* [Sweden](https://sweden.se/society/sweden-and-corona-in-brief/)





# References
